#!/bin/sh

test -f /tmp/xbmc.once || for i in $(seq 60); do pgrep psplash || break; sleep 1; done
touch /tmp/xbmc.once

export HOME=/home/xbmc
echo 3 > /proc/sys/vm/drop_caches
test -d /tmp/xbmc || setuidgid xbmc mkdir /tmp/xbmc
rm -f ${HOME}/.xbmc/temp
setuidgid xbmc ln -s /tmp/xbmc ${HOME}/.xbmc/temp

exec 2>&1 start-stop-daemon -S --pidfile /run/xbmc.pid --make-pidfile --chuid xbmc --exec /imx6/xbmc/lib/xbmc/xbmc.bin
