#!/bin/sh

test -f /tmp/xbmc.once || for i in $(seq 60); do pgrep psplash || break; sleep 1; done
touch /tmp/xbmc.once

export HOME=/home/xbmc
echo 3 > /proc/sys/vm/drop_caches

test -w /sys/module/galcore/parameters/gpu3DMinClock && echo 3 > /sys/module/galcore/parameters/gpu3DMinClock

test -d ${HOME} && chown xbmc:users ${HOME}
test -d ${HOME}/@APPLICATION_DIRECTORY@ || setuidgid xbmc mkdir ${HOME}/@APPLICATION_DIRECTORY@

test -d /tmp/xbmc || setuidgid xbmc mkdir /tmp/xbmc
rm -f ${HOME}/@APPLICATION_DIRECTORY@/temp
setuidgid xbmc ln -s /tmp/xbmc ${HOME}/@APPLICATION_DIRECTORY@/temp

insmod /lib/modules/4.1.*/extra/galcore.ko
exec 2>&1 start-stop-daemon -S --pidfile /run/xbmc.pid --make-pidfile --chuid xbmc --exec @APPLICATION_BIN@
rmmod /lib/modules/4.1.*/extra/galcore.ko
