#!/bin/sh 

test -f /tmp/sysimg_update.once || rm -rf /data/.update/*
test -f /tmp/sysimg_update.once || sleep 5m
touch /tmp/sysimg_update.once

if [ `stat -c "%s" /var/log/sysimg_update.log` -gt 1048576 ]
then
    mv /var/log/sysimg_update.log /var/log/sysimg_update.log.old
    xz /var/log/sysimg_update.log.old
fi
exec /usr/bin/sysimg_update
