#! /bin/bash
### BEGIN INIT INFO
# Provides:          ZWay
# Required-Start:    networking ifupdown $local_fs
# Required-Stop:     networking ifupdown $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Rademacher ZWay Service
# Description:       Rademacher ZWay Service
### END INIT INFO

zway_home="/opt/z-way"

exec_zway="$zway_home/z-way-server"
exec_zway_pid="/var/run/z-way-server.pid"

function _start_zway {
	# XXX check status!
	if [ ! -e /dev/ttyUSB0 ];
	then
		echo "Creating symlink..."
		ln -s /dev/ttyUSB1 /dev/ttyUSB0
		echo "Done"
	fi
	echo "Starting Z-Way"
	exec "${exec_zway}" &
	echo $! > ${exec_zway_pid}
}

function _stop_zway {
      	if [ -e "${exec_zway_pid}" ];
	then
                echo "Stopping Z-Way"
		kill $(cat "${exec_zway_pid}")
		rm -f "${exec_zway_pid}"
	fi
}

set -e

# Some things that run always
touch /var/lock/homepilot

case "$1" in
        start)
		_start_zway
	;;	
        stop)
		_stop_zway
	;;
        *)
                echo "Usage: /etc/init.d/z-way-server {start|stop}"
                exit 1
        ;;
esac

exit 0

