#!/bin/sh

set -e
set -x

test -n "$APPLY_TS" || exit 1
test -n "$TARGETS" || exit 1

MACHINE=`grep MACHINE conf/local.conf | sed -E -e "s/[^']+'([^']+)'.*/\\1/"`
DEPLOY_DIR_IMAGE="tmp/deploy/images/${MACHINE}"

# possible values are md5 rmd160 sha1 sha256 sha384 sha512 tiger whirlpool
ALGORITHMS="md5 rmd160 sha1"

SYSIMG_VERSION=$(. ${DEPLOY_DIR_IMAGE}/.settings; echo ${SYSIMG_VER})
MANI=""
MANISPC=""

for IMAGE in ${DEPLOY_DIR_IMAGE}/*-complete-${SYSIMG_VERSION}.cpi
do
    SPC=""
    HASH=""
    for alg in ${ALGORITHMS}
    do
	HASH="${HASH}${SPC}${alg}=`/opt/pkg/bin/digest ${alg} "${IMAGE}" | awk '{print $4}'`"
	SPC=";"
    done
    HASH="${HASH}${SPC}size=`stat -c %s "${IMAGE}"`"
    IMAGE=`echo ${IMAGE} | sed -e "s,${DEPLOY_DIR_IMAGE}/,,"`
    NAME=`echo ${IMAGE} | sed -e "s,rdm-,," -e "s,-image-complete-${SYSIMG_VERSION}.cpi,," -e 's,-,+,g'`
    MANI="${MANI}${MANISPC}\"${NAME}\": \"${IMAGE};${HASH}\""
    MANISPC=",
        "
done

APPLY_ISO="$APPLY_TS"
test "x$APPLY_TS" = "xnull" || APPLY_ISO="\"`date -d "${APPLY_TS}" --iso-8601=seconds | sed -e 's/+.*//g'`\""

MANIFEST="{
    \"${SYSIMG_VERSION}\": {
        ${MANI},
        \"apply\": ${APPLY_ISO}
    }
}"

# XXX do a rsync instead ...
for target in ${TARGETS}
do
    ssh "${USER}@${target}" "mkdir -p /var/tmp/${SYSIMG_VERSION}-nightly"
    echo "$MANIFEST" | ssh "${USER}@${target}" "cat >/var/tmp/${SYSIMG_VERSION}-nightly/manifest.json"
    (cd ${DEPLOY_DIR_IMAGE} && scp *-complete-${SYSIMG_VERSION}.cpi post-flash-${SYSIMG_VERSION}.tar.bz2 "${USER}@${target}:/var/tmp/${SYSIMG_VERSION}-nightly/")

    ssh "${USER}@${target}" "sudo /opt/pkg/bin/image-import --directory /var/tmp/${SYSIMG_VERSION}-nightly/"
done
