#!/bin/sh

set -x

MKIMGS="`echo $0 | sed -e 's/mkdeployimgs/mkimgs/'`"
MACHINE=`grep MACHINE conf/local.conf | sed -E -e "s/[^']+'([^']+)'.*/\\1/"`
DEPLOY_DIR_IMAGE="tmp/deploy/images/${MACHINE}"

bitbake -c compile -f virtual/kernel
"${MKIMGS}" rdm-hp2-xbmc-image
"${MKIMGS}" rdm-hp2-image
(cd `dirname $0`/post-flash && tar cjf - .) >${DEPLOY_DIR_IMAGE}/post-flash.tar.bz2
