#!/bin/sh

set -x

IMGSPC=""
BUILD_IMAGES=""
IMAGES=""

for IMAGE in "$@"
do
    RECOVERY_IMAGE="rdm-core-image"

    echo $IMAGE | fgrep -e "-dev-image"
    test $? -eq 0 && RECOVERY_IMAGE="rdm-core-dev-image"

    IMAGES="${IMAGES}${IMGSPC}${IMAGE}"
    BUILD_IMAGES="${BUILD_IMAGES}${IMGSPC}${IMAGE}"
    IMGSPC=" "
    echo ${IMAGES} | fgrep -e "${RECOVERY_IMAGE}"
    if [ "$?" != "0" ]
    then
	IMAGES="${IMAGES} ${RECOVERY_IMAGE}"
    fi
done

set -e

BITBAKE_OPTIONS="-k"
bitbake ${BITBAKE_OPTIONS} ${IMAGES} || bitbake ${IMAGES}

BITBAKE_SETTINGS=`bitbake -e system-image | egrep "(KERNEL_DEVICETREE|UBOOT_SUFFIX|UBOOT_PADDING|PV|MACHINE_ARCH|SDCARD_IMAGE|USBSTICK_IMAGE|KERNEL_IMAGETYPE)=" | sed -e "s/MACHINE_ARCH/MACHINE/" -e "s/PV/SYSIMG_VERSION/" -e "s/KERNEL_DEVICETREE/KERNEL_DEVICE_TREE/"`
eval $BITBAKE_SETTINGS
test -z "${UBOOT_PADDING}" && UBOOT_PADDING=0
test -z "${SDCARD_IMAGE}" && SDCARD_IMAGE=0
test -z "${USBSTICK_IMAGE}" && USBSTICK_IMAGE=0
test "${USBSTICK_IMAGE}" -eq 1 && SDCARD_IMAGE=0

DEPLOY_DIR_IMAGE="tmp/deploy/images/${MACHINE}"

PREFIX=""
test $SDCARD_IMAGE -eq 1 && PREFIX="sd"
test $USBSTICK_IMAGE -eq 1 && PREFIX="usb"
LABEL="${PREFIX}${MACHINE}"

script_bin="`readlink ${DEPLOY_DIR_IMAGE}/bootscript`"
kernel_bin="`readlink ${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}-${MACHINE}.bin`"
kernel_dtb="`readlink ${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}-${KERNEL_DEVICE_TREE} || true`"

KERNEL="${kernel_bin} ${script_bin}"
KERNEL_PREPARE="mv ${kernel_bin} ${KERNEL_IMAGETYPE}-${MACHINE} && mv ${script_bin} bootscript"
KERNEL_RECOVERY="ln -f ${KERNEL_IMAGETYPE} ${KERNEL_IMAGETYPE}-${MACHINE}"
KERNEL_SANITIZE="mv ${KERNEL_IMAGETYPE}-${MACHINE} ${KERNEL_IMAGETYPE}"
KERNEL_FILES="${KERNEL_IMAGETYPE}-${MACHINE}.bin ${kernel_bin} bootscript ${script_bin}"
if [ -n "${KERNEL_DEVICE_TREE}" ]
then
    for DTS_FILE in ${KERNEL_DEVICE_TREE}
    do
	DTS_BASE_NAME=`basename ${DTS_FILE} | awk -F "." '{print $1}'`
	if [ -e "${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb" ]
	then
	    bin_for_dtb="`readlink ${DEPLOY_DIR_IMAGE}/${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb`"
	    kernel_bin_for_dtb="`echo ${bin_for_dtb} | sed "s,$DTS_BASE_NAME,${MACHINE},g;s,\.dtb$,.bin,g"`"
	    if [ $kernel_bin = $kernel_bin_for_dtb ]
	    then
		KERNEL_FILES="${KERNEL_FILES} ${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb ${bin_for_dtb}"
		KERNEL="${KERNEL} ${bin_for_dtb}"
		KERNEL_PREPARE="${KERNEL_PREPARE} && mv ${bin_for_dtb} ${DTS_BASE_NAME}.dtb"
		# KERNEL_RECOVERY="${KERNEL_RECOVERY} && ln -f ${KERNEL_IMAGETYPE}-${MACHINE}-${DTS_BASE_NAME}.dtb ${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb"
		# KERNEL_SANITIZE="${KERNEL_SANITIZE} && mv ${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb ${KERNEL_IMAGETYPE}-${DTS_BASE_NAME}.dtb"
	    fi
	fi
    done
fi

for IMAGE in ${BUILD_IMAGES}
do
    SYSIMG_FILES=".${IMAGE}-${SYSIMG_VERSION}-settings .settings"
    FILES="${SYSIMG_FILES} ${KERNEL_FILES}"
    DEV=0
    RECOVERY_IMAGE="rdm-core-image"

    set +e
    echo $IMAGE | fgrep -e "-dev-image"
    test $? -eq 0 && DEV=1
    test "$DEV" -eq 1 && RECOVERY_IMAGE="rdm-core-dev-image"
    set -e

    uboot_bin="`readlink ${DEPLOY_DIR_IMAGE}/u-boot-${MACHINE}.${UBOOT_SUFFIX}`"
    FILES="${FILES} u-boot-${MACHINE}.${UBOOT_SUFFIX} ${uboot_bin}"

    rootimg="`readlink ${DEPLOY_DIR_IMAGE}/${IMAGE}-${MACHINE}.squashfs-xz`"
    FILES="${FILES} ${rootimg}"

    recimg="`readlink ${DEPLOY_DIR_IMAGE}/${RECOVERY_IMAGE}-${MACHINE}.squashfs-xz`"
    FILES="${FILES} ${recimg}"

cat >${DEPLOY_DIR_IMAGE}/.${IMAGE}-${SYSIMG_VERSION}-settings <<EOS
SYSIMG_VER=${SYSIMG_VERSION}
DEV=${DEV}
MACHINE=${MACHINE}
UBOOT_BIN=${uboot_bin}
UBOOT_PADDING="${UBOOT_PADDING}"
KERNEL="${KERNEL}"
ROOTIMG=${rootimg}
RECOVERIMG=${recimg}
KERNEL_PREPARE="${KERNEL_PREPARE}"
KERNEL_RECOVERY="${KERNEL_RECOVERY}"
KERNEL_SANITIZE="${KERNEL_SANITIZE}"
SDCARD_IMAGE="${SDCARD_IMAGE}"
USBSTICK_IMAGE="${USBSTICK_IMAGE}"
LABEL="${LABEL}"
EOS

    # XXX change next line into ln -sf after next applied update ...
    (cd ${DEPLOY_DIR_IMAGE} && cp -f .${IMAGE}-${SYSIMG_VERSION}-settings .settings)
    (cd ${DEPLOY_DIR_IMAGE} && rm -f ${IMAGE}-${SYSIMG_VERSION}-complete.cpi)
    (cd ${DEPLOY_DIR_IMAGE} && tar cjf ${IMAGE}-${SYSIMG_VERSION}-complete.cpi ${FILES})
    (cd ${DEPLOY_DIR_IMAGE} && ln -sf ${IMAGE}-${SYSIMG_VERSION}-complete.cpi ${IMAGE}-complete.cpi)
done
