#!/bin/sh

sudo -u homepilot /bin/sh /home/homepilot/bin/init_appdir.sh

# XXX must be able to be deleted
mkdir -p /etc/modules-load.d

hp_home="/opt/homepilot"
java_home="/usr/java"
java_elf="$java_home/bin/java"

exec sudo -u homepilot -- /bin/sh -c "cd $hp_home/lib/java && $java_elf -jar homepilot.jar"
