#!/bin/sh

listen_port=8079
log_out="/dev/null"
jetty_home="/opt/homepilot/opt/jetty"
java_home="/usr/java"
java_elf="$java_home/bin/java"

exec sudo -i -u homepilot -- /bin/sh -c "cd $jetty_home && exec $java_elf -jar start.jar -Djetty.port=$listen_port > $log_out 2>&1"
