#!/bin/sh

MAC=`sed -e 's/://g' /sys/class/net/eth0/address`
PORT=`ssh -T -i /var/lib/dropbear/dropbear_rsa_host_key -p 22 ${MAC}@homepilot.de | awk '{print $2}'`
chmod 644 /var/lib/dropbear/dropbear_rsa_host_key
if ! [[ $PORT =~ ^[0-9]+$ ]]; then sleep 60; exit 1; fi
exec ssh -T -i /var/lib/dropbear/dropbear_rsa_host_key -p 22 -K 10 -R ${PORT}:localhost:80 ${MAC}@homepilot.de -N 2>&1
